version: '3'
services:
  database:
    image: mariadb:10.8
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:3306"
    expose:
      - "${DB_PORT}"
    volumes:
      - database:/var/lib/mysql
      - "./docker/scripts/00-mysql-init.sh:/docker-entrypoint-initdb.d/mysql-init.sh"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  database:
